x-internal-secret: &internal-secret
  INTERNAL_SECRET: "AAAAAAAAAAAAAAAAAAAAAAA"


services:
  #API AUTH
  mongo-auth:
    image: mongo
    container_name: mongo-auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passadmin
    volumes:
      - mongo-auth:/persist/auth
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - gatcha-lan

  api-auth:
    build: 
      context: API_AUTH/
    container_name: api-auth
    ports:
      - "8080:8080"
    networks:
      - gatcha-lan

  #API JOUEUR
  mongo-joueur:
    image: mongo
    container_name: mongo-joueur
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passadmin
    volumes:
      - mongo-joueur:/persist/joueur
    expose:
      - 27018
    ports:
      - "27018:27017"
    restart: on-failure
    networks:
      - gatcha-lan

  api-joueur:
    environment:
      <<: *internal-secret
    build: 
      context: API_JOUEUR/
      
    container_name: api-joueur
    ports:
      - "8081:8080"
    networks:
      - gatcha-lan



  # API MONSTRES
  mongo-monstres:
    image: mongo
    container_name: mongo-monstres
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passadmin
    volumes:
      - mongo-monstres:/persist/monstres
    expose:
      - 27018
    ports:
      - "27019:27017"
    restart: on-failure
    networks:
      - gatcha-lan

  api-monstres:
    environment:
      <<: *internal-secret
    build:
      context: API_MONSTRES/

    container_name: api-monstres
    ports:
      - "8082:8080"
    networks:
      - gatcha-lan


  # API INVOCATION
  mongo-invocation:
    image: mongo
    container_name: mongo-invocation
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passadmin
    volumes:
      - mongo-invocation:/persist/invocation
    expose:
      - 27018
    ports:
      - "27020:27017"
    restart: on-failure
    networks:
      - gatcha-lan

  api-invocation:
    environment:
      <<: *internal-secret
    build:
      context: API_INVOCATIONS/

    container_name: api-invocation
    ports:
      - "8083:8080"
    networks:
      - gatcha-lan

volumes:
  mongo-auth:
  mongo-joueur:
  mongo-invocation:
  mongo-monstres:


networks:
  gatcha-lan:
    external: true

